# This is a Docker Compose configuration
# intended for development purposes only

version: '3'

volumes:
  db: {}
  caddy_data:
  caddy_config:

services:
  db:
    image: mysql:8
    env_file:
      - dev.env
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./dev/docker/init.db:/docker-entrypoint-initdb.d
      - db:/var/lib/mysql
  app:
    build:
      context: .
      dockerfile: ./dev/docker/Dockerfile
    env_file:
      - dev.env
    ports:
      - ${DEV_PORT:-8080}:80
    volumes:
      - ./:/app
      - ./dev/docker/php/conf.d/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
    entrypoint: /app/dev/docker/entrypoint.app.sh

  node:
    image: node:alpine
    working_dir: /app
    user: node
    volumes:
      - ./:/app
    entrypoint: /app/dev/docker/entrypoint.node.sh
  mailhog:
    image: mailhog/mailhog
    ports:
      - ${DEV_MAIL_PORT:-8025}:8025
  mercure:
    image: dunglas/mercure
    restart: unless-stopped
    env_file:
      - dev.env
    environment:
      MERCURE_EXTRA_DIRECTIVES: cors_origins "http://bookstack.local"
    # Uncomment the following line to enable the development mode
    #command: /usr/bin/caddy run -config /etc/caddy/Caddyfile.dev
    ports:
      - "3000:80"
    volumes:
      - caddy_data:/data
      - caddy_config:/config
